import type{Tutor}from'../types';import{paths,skills as featuredSkills,tutors as mockTutors}from'../data/mock';import{api,offlineFallback}from'./api';
export type Skill={id:string;name:string};
export type TutorApplication={firstName:string;lastName:string;country:string;timezone:string;headline:string;bio:string;yearsOfExperience:number;teachingExperience:string;avatar:null;githubUrl:string|null;portfolioUrl:string|null;linkedinUrl:string|null;hourlyRate:number;trialRate:number;languages:string[];skills:{skillId:string;yearsExperience:number;skillLevel:'EXPERT';isPrimary:boolean}[];availability:Record<string,{start:string;end:string}[]>};
// Offline, the catalogue is every skill the demo data already teaches, across all domains.
const offlineSkills=():Skill[]=>[...new Set([...featuredSkills.map(s=>s.name),...mockTutors.flatMap(t=>t.skills),...paths.flatMap(p=>p.skills)])].sort((a,b)=>a.localeCompare(b)).map(name=>({id:name.toLowerCase().replace(/[^a-z0-9+#]+/g,'-'),name}));
const APPLICATION_KEY='pairlore.tutor-application';
type ApiTutor={id:string;headline:string|null;bio:string|null;country:string|null;hourlyRate:number|null;trialRate:number|null;yearsOfExperience:number;teachingExperience:string|null;averageRating:number;totalReviews:number;totalStudents:number;lessonsCompleted:number;languages:string[];availability:unknown;user:{firstName:string;lastName:string;avatar:string|null;country:string|null};skills:{skill:{name:string}}[]};
const adapt=(t:ApiTutor):Tutor=>({id:t.id,name:`${t.user.firstName} ${t.user.lastName}`,location:t.country??t.user.country??'Remote',headline:t.headline??'Programming tutor',skills:t.skills.map(x=>x.skill.name),rating:t.averageRating,reviews:t.totalReviews,students:t.totalStudents,lessons:t.lessonsCompleted,price:t.hourlyRate??0,bio:t.bio??'',available:Boolean(t.availability),image:t.user.avatar??`${t.user.firstName[0]}${t.user.lastName[0]}`,experience:t.yearsOfExperience,languages:t.languages,speciality:t.teachingExperience??'Personalized lessons'});
const filterMocks=(params:URLSearchParams)=>{const skill=params.get('skill');return skill?mockTutors.filter(t=>t.skills.some(s=>s.toLowerCase().replaceAll(' ','-')===skill)):mockTutors};
export const tutorService={list:async(params:URLSearchParams)=>{try{const data=await api<{items:ApiTutor[];pagination:{page:number;pages:number;total:number}}>(`/tutors?${params}`);return{...data,items:data.items.map(adapt)}}catch{const items=filterMocks(params);return{items,pagination:{page:1,pages:1,total:items.length}}}},detail:async(id:string)=>{try{return adapt((await api<{tutor:ApiTutor}>(`/tutors/${id}`)).tutor)}catch{return mockTutors.find(t=>t.id===id)??mockTutors[0]!}},
 skills:()=>offlineFallback(()=>api<{skills:Skill[]}>('/skills').then(r=>r.skills),async()=>offlineSkills()),
 submitOnboarding:(application:TutorApplication)=>offlineFallback(()=>api<unknown>('/tutors/onboarding',{method:'PUT',body:JSON.stringify(application)}).then(()=>undefined),async()=>{try{localStorage.setItem(APPLICATION_KEY,JSON.stringify({...application,submittedAt:new Date().toISOString()}))}catch{/* storage blocked: the demo flow still completes */}})};
