import type{Tutor}from'../types';import{paths,skills as featuredSkills,tutors as mockTutors}from'../data/mock';import{countries}from'../data/locations';import{ApiError,api,offlineFallback}from'./api';
export type Skill={id:string;name:string};
export type TutorStatus='draft'|'submitted'|'approved'|'rejected';
export type TutorProfileInput={headline:string;bio:string;yearsOfExperience:number;teachingExperience:string;languages:string[];hourlyRate:number;trialRate:number;githubUrl:string;portfolioUrl:string;linkedinUrl:string;skills:{code:string;yearsExperience:number;isPrimary:boolean}[]};
export type TutorProfile=Omit<TutorProfileInput,'githubUrl'|'portfolioUrl'|'linkedinUrl'|'skills'>&{id:string;firstName:string;lastName:string;country:string|null;timezone:string;currency:string;githubUrl:string|null;portfolioUrl:string|null;linkedinUrl:string|null;status?:TutorStatus;skills:{code:string;name:string;yearsExperience:number;isPrimary:boolean}[]};
// Offline, the catalogue is every skill the demo data already teaches, across all domains.
const offlineSkills=():Skill[]=>[...new Set([...featuredSkills.map(s=>s.name),...mockTutors.flatMap(t=>t.skills),...paths.flatMap(p=>p.skills)])].sort((a,b)=>a.localeCompare(b)).map(name=>({id:name.toLowerCase().replace(/[^a-z0-9+#]+/g,'-'),name}));
const PROFILE_KEY='pairlore.tutor-profile';
const countryName=(code:string|null)=>countries.find(c=>c.code===code)?.label??'Remote';
// Ratings and lesson counts arrive with reviews and sessions; until then a new tutor starts at zero.
const adapt=(t:TutorProfile):Tutor=>({id:t.id,name:`${t.firstName} ${t.lastName}`,location:countryName(t.country),headline:t.headline,skills:t.skills.map(s=>s.name),skillCodes:t.skills.map(s=>s.code),rating:0,reviews:0,students:0,lessons:0,price:t.hourlyRate,bio:t.bio,available:true,image:`${t.firstName[0]??''}${t.lastName[0]??''}`,experience:t.yearsOfExperience,languages:t.languages,speciality:t.teachingExperience||t.skills[0]?.name||'Personalised lessons'});
const filterMocks=(params:URLSearchParams)=>{const skill=params.get('skill');return skill?mockTutors.filter(t=>t.skills.some(s=>s.toLowerCase().replaceAll(' ','-')===skill)):mockTutors};
const readSaved=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)??'null') as TutorProfile|null}catch{return null}};
export const tutorService={list:async(params:URLSearchParams)=>{try{const data=await api<{items:TutorProfile[];pagination:{page:number;pages:number;total:number}}>(`/tutors?${params}`);return{...data,items:data.items.map(adapt)}}catch{const items=filterMocks(params);return{items,pagination:{page:1,pages:1,total:items.length}}}},detail:async(id:string)=>{try{return adapt((await api<{tutor:TutorProfile}>(`/tutors/${id}`)).tutor)}catch{return mockTutors.find(t=>t.id===id)??mockTutors[0]!}},
 skills:()=>offlineFallback(()=>api<{code:string;label:string}[]>('/reference/skills').then(items=>items.map(item=>({id:item.code,name:item.label}))),async()=>offlineSkills()),
 /** The signed-in tutor's own profile, or null before they have saved one. */
 myProfile:()=>offlineFallback(()=>api<{tutor:TutorProfile}>('/tutor/profile').then(r=>r.tutor).catch(e=>{if(e instanceof ApiError&&e.status===404)return null;throw e}),async()=>readSaved()),
 /** Saving a complete profile submits it for review; an approved one stays live. */
 saveProfile:(input:TutorProfileInput)=>offlineFallback(()=>api<{tutor:TutorProfile}>('/tutor/profile',{method:'PUT',body:JSON.stringify(input)}).then(r=>r.tutor),async()=>{const saved={...input,id:'offline',firstName:'',lastName:'',country:null,timezone:'UTC',currency:'USD',status:'submitted' as const,githubUrl:input.githubUrl||null,portfolioUrl:input.portfolioUrl||null,linkedinUrl:input.linkedinUrl||null,skills:input.skills.map(s=>({...s,name:s.code}))};try{localStorage.setItem(PROFILE_KEY,JSON.stringify(saved))}catch{/* storage blocked: the demo flow still completes */}return saved})};
