import{useEffect,useState}from'react';import{Link,useNavigate,useParams}from'react-router-dom';import{Camera,CameraOff,Check,ChevronDown,Clock,Lock,Mic,MicOff,Settings,Speaker,Video}from'lucide-react';
import{ledgerService}from'../services/ledger.service';
import{useAuth}from'../auth';
import{formatMoney,relativeTime}from'../lib/money';
import type{SessionPayment}from'../types/payments';

/** The lobby is the handoff into the room, so it shows the session that was actually booked. */
function useBookedSession(sessionId:string|undefined){
 const[session,setSession]=useState<SessionPayment|null>(null);
 useEffect(()=>{
  if(!sessionId)return;
  let live=true;
  ledgerService.bySession(sessionId).then(found=>{if(live)setSession(found)}).catch(()=>{/* the lobby still works without it */});
  return()=>{live=false};
 },[sessionId]);
 return session;
}
const initials=(name:string)=>name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();export function LessonLobby(){const{bookingId}=useParams();const navigate=useNavigate();const[cam,setCam]=useState(true);const[mic,setMic]=useState(true);const[testing,setTesting]=useState(false);const{user}=useAuth();const session=useBookedSession(bookingId);
 /* The lobby is shared by both sides, so it names whoever you are meeting — not whoever teaches. */
 const meeting=session?(user?.id===session.payeeId?{name:session.payerName,role:'Learner'}:{name:session.payeeName,role:session.skill?`${session.skill} tutor`:'Tutor'}):null;const when=session?.startsAt?new Date(session.startsAt):null;return <main className="lesson-lobby"><header><Link to="/"><span>⌘</span> pairlore</Link><span>Having trouble? <button>Get help</button></span></header><div className="lobby-layout"><section className="device-preview"><div className={cam?'preview-active':'preview-off'}><div className="preview-avatar">DO</div>{cam?<span>Camera preview</span>:<><CameraOff/><strong>Your camera is off</strong></>}</div><div className="preview-controls"><button className={!mic?'off':''} onClick={()=>setMic(!mic)}>{mic?<Mic/>:<MicOff/>}</button><button className={!cam?'off':''} onClick={()=>setCam(!cam)}>{cam?<Camera/>:<CameraOff/>}</button><button><Settings/></button></div></section><aside><span className="lobby-time"><Clock/> {when?`Your session starts ${relativeTime(when.toISOString())}`:'Your lesson starts in 8 minutes'}</span><div className="lobby-tutor"><div className="avatar">{meeting?initials(meeting.name):'SC'}</div><div><strong>{meeting?.name??'Sarah Chen'}</strong><span>{meeting?.role??'JavaScript tutor · 4.98 ★'}</span></div></div><h1>{session?.topic??'JavaScript Array Methods'}</h1><div className="lesson-facts"><p><span>Date</span>{when?when.toLocaleDateString('en',{weekday:'long',month:'short',day:'numeric',year:'numeric'}):'Thursday, Sep 3, 2026'}</p><p><span>Time</span>{when?when.toLocaleTimeString('en',{hour:'numeric',minute:'2-digit'}):'3:00 PM'} · {Intl.DateTimeFormat().resolvedOptions().timeZone}</p><p><span>Duration</span>{session?.scheduledMinutes??60} minutes</p>{session&&<p><span>Rate</span>{formatMoney(session.hourlyRate,session.currency)} / hour</p>}</div>{session&&<p className="lobby-escrow"><Lock size={13}/> {formatMoney(session.heldAmount,session.currency)} is held for this session. You are billed for the minutes taught.</p>}<div className="device-checks"><button onClick={()=>{setTesting(true);setTimeout(()=>setTesting(false),1200)}}><Mic/><span><strong>Microphone</strong>{testing?'Testing…':'Built-in microphone'}</span>{testing?<i className="audio-bars"/>:<Check/>}</button><button><Speaker/><span><strong>Speaker</strong>Default output</span><Check/></button><button><Video/><span><strong>Camera</strong>Integrated camera</span><ChevronDown/></button></div><button className="btn lobby-join" onClick={()=>navigate(`/lesson/${bookingId}`)}>Join lesson</button><button className="join-without" onClick={()=>{setCam(false);navigate(`/lesson/${bookingId}`)}}>Join without camera</button></aside></div></main>}
