import{Component,lazy,Suspense,useEffect,useLayoutEffect}from'react';
import{Route,Routes,useLocation,useNavigationType}from'react-router-dom';
import{PublicLayout}from'./layouts';
import{ProtectedRoute}from'./route-guard';import{ForgotPasswordPage,ResetPasswordPage,VerifyEmailPage}from'./account-pages';
import{BecomeTutor,Home,NotFound}from'./pages';
import{LearningPathDetail,LearningPaths}from'./paths-pages';
import{Messages}from'./messages-page';
import{AssignmentsPage}from'./assignments-page';
import{AuthPage}from'./connected-pages';import{TutorOnboarding}from'./tutor-onboarding';import{TutorProfile,Tutors}from'./tutors-page';import{WorkspacePicker}from'./workspace-picker';
import{FrontendBooking}from'./booking-frontend';
import{AdminControlCentre}from'./admin-control';
import{NotificationsPage,StudentTutors,TutorCalendar}from'./workspace-pages';import{LessonsPage}from'./lessons-page';import{TutorDashboard}from'./tutor-dashboard';import{TutorStudents}from'./tutor-students';import{SettingsPage}from'./settings-page';import{StudentDashboard}from'./student-dashboard';
import{WalletPage}from'./wallet-pages';
import{TutorReviewsPage}from'./reviews-pages';
import{AppealsPage,SessionPaymentsPage}from'./ledger-pages';
import{LearnerAdsPage,TutorAdBoardPage}from'./learning-ads-pages';
import{AcceptInvitePage,OrgDashboard,OrgInvitations,OrgTrainers}from'./org-pages';

const PremiumLessonRoom=lazy(()=>import('./classroom/LessonRoom').then(m=>({default:m.PremiumLessonRoom})));
const LessonLobby=lazy(()=>import('./classroom/LessonLobby').then(m=>({default:m.LessonLobby})));
const LessonSummary=lazy(()=>import('./classroom/LessonSummary').then(m=>({default:m.LessonSummary})));
const Student=({children}:{children:React.ReactNode})=><ProtectedRoute roles={['STUDENT']}>{children}</ProtectedRoute>;
const Tutor=({children}:{children:React.ReactNode})=><ProtectedRoute roles={['TUTOR']}>{children}</ProtectedRoute>;
const Org=({children}:{children:React.ReactNode})=><ProtectedRoute roles={['ORGANIZATION']}>{children}</ProtectedRoute>;
const Workspace=({children}:{children:React.ReactNode})=><ProtectedRoute roles={['STUDENT','TUTOR']}>{children}</ProtectedRoute>;

function RouteTitle(){const{pathname}=useLocation();useEffect(()=>{const exact:Record<string,string>={'/':'Learn from experts across tech','/tutors':'Find a tutor','/learning-paths':'Learning paths','/become-a-tutor':'Become a tutor','/login':'Log in','/signup':'Create account','/forgot-password':'Reset password','/reset-password':'Choose a new password','/verify-email':'Verify email','/student/dashboard':'Student dashboard','/tutor/dashboard':'Tutor dashboard','/admin':'Admin control centre','/org/dashboard':'Organisation dashboard','/org/trainers':'Organisation trainers','/org/invitations':'Trainer invitations'};let title=exact[pathname];if(!title&&pathname.startsWith('/tutor/'))title='Tutor profile';if(!title&&pathname.startsWith('/student/'))title=pathname.split('/').pop()!.replaceAll('-',' ');if(!title&&pathname.startsWith('/admin/'))title=`Admin ${pathname.split('/').filter(Boolean).pop()!.replaceAll('-',' ')}`;if(!title&&pathname.startsWith('/booking/'))title='Book a lesson';if(!title&&pathname.startsWith('/lesson/'))title=pathname.endsWith('/lobby')?'Lesson lobby':pathname.endsWith('/summary')?'Lesson summary':'Classroom';document.title=`${title?title[0]!.toUpperCase()+title.slice(1):'Page not found'} | Pairlore`},[pathname]);return null}
function RouteScroll(){const{pathname}=useLocation();const navigationType=useNavigationType();useLayoutEffect(()=>{if(navigationType!=='POP')window.scrollTo({top:0,left:0,behavior:'auto'})},[pathname,navigationType]);return null}
class AppErrorBoundary extends Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){if(this.state.failed)return <main className="fatal-error"><div><h1>Something went wrong.</h1><p>We couldn’t display this page. Your preview data is still safe.</p><button className="btn" onClick={()=>this.setState({failed:false})}>Try again</button><a className="btn ghost" href="/">Return home</a></div></main>;return this.props.children}}

export default function App(){return <AppErrorBoundary><RouteTitle/><RouteScroll/><Suspense fallback={<div className="placeholder"><div className="loading-spinner"/><p>Preparing your workspace…</p></div>}><Routes>
 <Route element={<PublicLayout/>}><Route path="/" element={<Home/>}/><Route path="/tutors" element={<Tutors/>}/><Route path="/tutors/:skill" element={<Tutors/>}/><Route path="/tutor/:id" element={<TutorProfile/>}/><Route path="/learning-paths" element={<LearningPaths/>}/><Route path="/learning-paths/:slug" element={<LearningPathDetail/>}/><Route path="/become-a-tutor" element={<BecomeTutor/>}/></Route>
 <Route path="/choose-workspace" element={<WorkspacePicker/>}/><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/signup" element={<AuthPage mode="signup"/>}/><Route path="/forgot-password" element={<ForgotPasswordPage/>}/><Route path="/reset-password" element={<ResetPasswordPage/>}/><Route path="/verify-email" element={<VerifyEmailPage/>}/><Route path="/invite/:token" element={<AcceptInvitePage/>}/><Route path="/booking/:tutorId" element={<Student><FrontendBooking/></Student>}/>
 <Route path="/lesson/:bookingId/lobby" element={<Workspace><LessonLobby/></Workspace>}/><Route path="/lesson/:bookingId/summary" element={<Workspace><LessonSummary/></Workspace>}/><Route path="/lesson/:bookingId" element={<Workspace><PremiumLessonRoom/></Workspace>}/><Route path="/messages/:conversationId" element={<Messages/>}/>
 <Route path="/student/dashboard" element={<Student><StudentDashboard/></Student>}/><Route path="/student/lessons" element={<Student><LessonsPage role="student"/></Student>}/><Route path="/student/lessons/:id" element={<Student><LessonsPage role="student"/></Student>}/><Route path="/student/tutors" element={<Student><StudentTutors/></Student>}/><Route path="/student/messages" element={<Student><Messages/></Student>}/><Route path="/student/messages/:conversationId" element={<Student><Messages/></Student>}/><Route path="/student/learning-paths" element={<Student><LearningPaths/></Student>}/><Route path="/student/assignments" element={<Student><AssignmentsPage role="student"/></Student>}/><Route path="/student/wallet" element={<Student><WalletPage role="student"/></Student>}/><Route path="/student/payments" element={<Student><SessionPaymentsPage role="student"/></Student>}/><Route path="/student/appeals" element={<Student><AppealsPage role="student"/></Student>}/><Route path="/student/learning-ads" element={<Student><LearnerAdsPage/></Student>}/><Route path="/student/notifications" element={<Student><NotificationsPage role="student"/></Student>}/><Route path="/student/settings" element={<Student><SettingsPage role="student"/></Student>}/><Route path="/student/saved-tutors" element={<Student><StudentTutors/></Student>}/>
 <Route path="/tutor/dashboard" element={<Tutor><TutorDashboard/></Tutor>}/><Route path="/tutor/onboarding" element={<Tutor><TutorOnboarding/></Tutor>}/><Route path="/tutor/students" element={<Tutor><TutorStudents/></Tutor>}/><Route path="/tutor/students/:id" element={<Tutor><TutorStudents/></Tutor>}/><Route path="/tutor/lessons" element={<Tutor><LessonsPage role="tutor"/></Tutor>}/><Route path="/tutor/calendar" element={<Tutor><TutorCalendar/></Tutor>}/><Route path="/tutor/messages" element={<Tutor><Messages/></Tutor>}/><Route path="/tutor/messages/:conversationId" element={<Tutor><Messages/></Tutor>}/><Route path="/tutor/assignments" element={<Tutor><AssignmentsPage role="tutor"/></Tutor>}/><Route path="/tutor/reviews" element={<Tutor><TutorReviewsPage/></Tutor>}/><Route path="/tutor/wallet" element={<Tutor><WalletPage role="tutor"/></Tutor>}/><Route path="/tutor/earnings" element={<Tutor><SessionPaymentsPage role="tutor"/></Tutor>}/><Route path="/tutor/withdrawals" element={<Tutor><WalletPage role="tutor"/></Tutor>}/><Route path="/tutor/appeals" element={<Tutor><AppealsPage role="tutor"/></Tutor>}/><Route path="/tutor/ad-board" element={<Tutor><TutorAdBoardPage/></Tutor>}/><Route path="/tutor/profile" element={<Tutor><SettingsPage role="tutor"/></Tutor>}/><Route path="/tutor/settings" element={<Tutor><SettingsPage role="tutor"/></Tutor>}/><Route path="/tutor/notifications" element={<Tutor><NotificationsPage role="tutor"/></Tutor>}/>
 <Route path="/org/dashboard" element={<Org><OrgDashboard/></Org>}/><Route path="/org/trainers" element={<Org><OrgTrainers/></Org>}/><Route path="/org/invitations" element={<Org><OrgInvitations/></Org>}/><Route path="/org/wallet" element={<Org><WalletPage role="org"/></Org>}/><Route path="/org/earnings" element={<Org><SessionPaymentsPage role="org"/></Org>}/>
 <Route path="/admin/*" element={<ProtectedRoute roles={['ADMIN']}><AdminControlCentre/></ProtectedRoute>}/><Route path="*" element={<NotFound/>}/>
 </Routes></Suspense></AppErrorBoundary>}
