import {useState} from 'react';
import {Link,NavLink,useNavigate} from 'react-router-dom';
import {useAuth,workspacePath} from './auth';
import {ArrowRight,Bell,BookOpen,Building2,CalendarDays,Check,ChevronDown,CircleDollarSign,ClipboardList,Code2,CreditCard,GraduationCap,Heart,Landmark,LayoutDashboard,LogOut,Mail,Megaphone,Menu,MessageCircle,Route as RouteIcon,Scale,Search,Settings,ShieldCheck,Sparkles,Star,UserRound,Users,Wallet,X,Zap} from 'lucide-react';
import type {LearningPath,Tutor} from './types';

export function Logo(){return <Link to="/" className="logo"><span><Code2 size={20}/></span>pair<span>lore</span></Link>}
export function Navbar(){const [open,setOpen]=useState(false);const {user,logout}=useAuth();const navigate=useNavigate();const close=()=>setOpen(false);const home=user?workspacePath(user.role):'/';const signOut=async()=>{close();await logout();navigate('/')};return <header className="nav"><div className="nav-inner"><Logo/><nav className={open?'nav-links open':'nav-links'} aria-label="Primary navigation"><NavLink to="/tutors" onClick={close}>Find tutors</NavLink><NavLink to="/learning-paths" onClick={close}>Learning paths</NavLink><NavLink to="/become-a-tutor" onClick={close}>Become a tutor</NavLink>{user?<NavLink to={home} className="mobile-login" onClick={close}>My workspace</NavLink>:<NavLink to="/login" className="mobile-login" onClick={close}>Log in</NavLink>}</nav><div className="nav-actions">{user?<><Link to={home} className="link-btn">My workspace</Link><button className="btn small ghost" onClick={signOut}>Log out</button></>:<><Link to="/login" className="link-btn">Log in</Link><Link to="/signup" className="btn small">Get started</Link></>}<button className="icon-btn menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></div></header>}
export function Footer(){return <footer><div className="footer-grid"><div><Logo/><p>One-on-one programming lessons from people who build software every day.</p></div><div><h4>Learn</h4><Link to="/tutors/python">Python tutors</Link><Link to="/tutors/javascript">JavaScript tutors</Link><Link to="/learning-paths">Learning paths</Link></div><div><h4>Teach</h4><Link to="/become-a-tutor">Become a tutor</Link><Link to="/become-a-tutor">Tutor resources</Link><Link to="/become-a-tutor">Tutor community</Link></div><div><h4>Company</h4><Link to="/">About Pairlore</Link><Link to="/student/settings">Help center</Link><Link to="/student/messages">Contact support</Link></div></div><div className="footer-bottom"><span>© 2026 pairlore</span><span>Privacy · Terms · Cookies</span></div></footer>}
export function Stars({rating}:{rating:number}){return <span className="rating"><Star size={15} fill="currentColor"/>{rating}</span>}
export function SkillBadge({children}:{children:string}){return <span className="badge">{children}</span>}
export function TutorCard({tutor,compact=false}:{tutor:Tutor;compact?:boolean}){return <article className={compact?'tutor-card compact':'tutor-card'}><button className="heart" aria-label="Save tutor"><Heart size={19}/></button><div className="avatar-wrap"><div className="avatar">{tutor.image}</div>{tutor.available&&<i/>}</div><div className="tutor-main"><div className="tutor-title"><div><h3><Link to={`/tutor/${tutor.id}`}>{tutor.name}</Link></h3><p>{tutor.location}</p></div><div className="tutor-price"><strong>${tutor.price}</strong><span>/ 50 min</span></div></div><h4>{tutor.headline}</h4><div className="badges">{tutor.skills.map(s=><SkillBadge key={s}>{s}</SkillBadge>)}</div>{!compact&&<p className="bio">{tutor.bio}</p>}<div className="tutor-meta"><Stars rating={tutor.rating}/><span>{tutor.reviews} reviews</span><span>·</span><span>{tutor.lessons.toLocaleString()} lessons</span></div><div className="card-actions"><Link className="btn ghost" to={`/tutor/${tutor.id}`}>View profile</Link><Link className="btn" to={`/booking/${tutor.id}`}>Book trial</Link></div></div></article>}
export function SearchBar({placeholder='What do you want to learn?'}:{placeholder?:string}={}){const [query,setQuery]=useState('');return <form className="searchbar" onSubmit={e=>{e.preventDefault();location.href=`/tutors/${query.toLowerCase().replaceAll(' ','-')}`}}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder} aria-label="Search skill"/><button className="btn">Find my tutor <ArrowRight size={17}/></button></form>}
export function PathCard({path}:{path:LearningPath}){return <article className="path-card"><div className="path-icon">{path.icon}</div><div className="path-label"><span>{path.level}</span><span>{path.duration}</span></div><h3>{path.name}</h3><p>{path.description}</p><div className="badges">{path.skills.slice(0,4).map(s=><SkillBadge key={s}>{s}</SkillBadge>)}</div>{path.progress!==undefined&&<div className="progress"><i style={{width:`${path.progress}%`}}/><span>{path.progress}% complete</span></div>}<Link to={`/learning-paths/${path.slug}`} className="text-link">Explore path <ArrowRight size={16}/></Link></article>}
export type TutorFilterState={skill:string;maxPrice:string;experience:string;rating:string;availability:string;language:string;speciality:string};
export function Filters({values,onChange,onReset,skills,languages,specialities}:{values:TutorFilterState;onChange:(key:keyof TutorFilterState,value:string)=>void;onReset:()=>void;skills:string[];languages:string[];specialities:string[]}){const field=(label:string,key:keyof TutorFilterState,options:[string,string][])=> <label className="filter-field"><span>{label}</span><select value={values[key]} onChange={event=>onChange(key,event.target.value)} aria-label={label}>{options.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select><ChevronDown size={16}/></label>;return <aside className="filters"><div className="filter-head"><h3>Filters</h3><button type="button" onClick={onReset}>Reset</button></div>{field('Subject','skill',[['','Any skill'],...skills.map(x=>[x,x] as [string,string])])}{field('Maximum price','maxPrice',[['','Any price'],['30','Up to $30'],['40','Up to $40'],['50','Up to $50'],['60','Up to $60']])}{field('Experience level','experience',[['','Any experience'],['3','3+ years'],['5','5+ years'],['8','8+ years']])}{field('Tutor rating','rating',[['','Any rating'],['4.8','4.8 and up'],['4.9','4.9 and up'],['4.95','4.95 and up']])}{field('Availability','availability',[['','Any availability'],['available','Available now'],['unavailable','Not currently available']])}{field('Language','language',[['','Any language'],...languages.map(x=>[x,x] as [string,string])])}{field('Speciality','speciality',[['','Any speciality'],...specialities.map(x=>[x,x] as [string,string])])}</aside>}
const dashboardNav={student:[['Overview','dashboard'],['My Lessons','lessons'],['My Tutors','tutors'],['Messages','messages'],['Learning Paths','learning-paths'],['Learning Ads','learning-ads'],['Assignments','assignments'],['Saved Tutors','saved-tutors'],['Wallet','wallet'],['Session Payments','payments'],['Appeals','appeals'],['Settings','settings']],tutor:[['Overview','dashboard'],['My Students','students'],['Lessons','lessons'],['Calendar','calendar'],['Messages','messages'],['Ad Board','ad-board'],['Assignments','assignments'],['Profile','profile'],['Reviews','reviews'],['Wallet','wallet'],['Earnings','earnings'],['Appeals','appeals'],['Withdrawals','withdrawals'],['Settings','settings']],org:[['Overview','dashboard'],['Trainers','trainers'],['Invitations','invitations'],['Wallet','wallet'],['Earnings','earnings']],admin:[['Dashboard',''],['Students','students'],['Tutors','tutors'],['Tutor Applications','applications'],['Lessons','lessons'],['Payments','payments'],['Withdrawals','withdrawals'],['Programming Skills','skills'],['Learning Paths','learning-paths'],['Reports','reports'],['Settings','settings']]};
const navIcon:Record<string,React.ReactNode>={dashboard:<LayoutDashboard/>,students:<Users/>,tutors:<GraduationCap/>,lessons:<BookOpen/>,calendar:<CalendarDays/>,messages:<MessageCircle/>,['learning-paths']:<RouteIcon/>,assignments:<ClipboardList/>,['saved-tutors']:<Heart/>,payments:<CreditCard/>,settings:<Settings/>,profile:<UserRound/>,reviews:<Star/>,wallet:<Wallet/>,earnings:<CircleDollarSign/>,appeals:<Scale/>,['learning-ads']:<Megaphone/>,['ad-board']:<Megaphone/>,withdrawals:<Landmark/>,applications:<ClipboardList/>,skills:<Code2/>,reports:<ClipboardList/>,trainers:<GraduationCap/>,invitations:<Mail/>,['']:<LayoutDashboard/>};
export function DashboardShell({role,children}:{role:'student'|'tutor'|'admin'|'org';children:React.ReactNode}){const {user,logout}=useAuth();const navigate=useNavigate();const demo=role==='student'?['AL','Alex Lee']:role==='tutor'?['DO','David Okafor']:role==='org'?['PR','Priya Raman']:['AD','Admin'];const roleLabel=role==='org'?(user?.orgName??'organisation'):role==='tutor'&&user?.orgName?user.orgName:role;const who=user?`${user.firstName} ${user.lastName}`:demo[1]!;const initials=user?`${user.firstName[0]??''}${user.lastName[0]??''}`.toUpperCase():demo[0]!;const signOut=async()=>{await logout();navigate('/')};return <div className="dash"><aside className="sidebar"><Logo/><div className="user-mini"><div className="avatar sm">{initials}</div><div><strong>{who}</strong><span>{roleLabel}</span></div></div><nav aria-label={`${role} workspace`}>{dashboardNav[role].map(([item,path])=><NavLink className={({isActive})=>isActive?'active':''} end={path===''||path==='dashboard'} key={item} to={role==='admin'?`/admin${path?`/${path}`:''}`:`/${role}/${path}`}><span>{navIcon[path]}</span>{item}</NavLink>)}</nav><div className="sidebar-footer"><Link to="/" className="back">← Back to marketplace</Link><button type="button" className="logout" onClick={signOut}><LogOut/><span>Log out</span></button></div></aside><main className="dash-main"><div className="dash-top"><div><span className="eyebrow">{role==="org"?"organisation":role} workspace</span></div><div className="dash-tools">{role!=='org'&&<><Link to={`/${role}/messages`} aria-label="Messages"><MessageCircle size={18}/></Link><Link className="top-notification" to={`/${role}/notifications`} aria-label="Notifications"><Bell size={18}/><i/></Link></>}<div className="avatar tiny">{initials}</div></div></div>{children}</main></div>}
export function StatCard({label,value,trend,icon}:{label:string;value:string;trend:string;icon:React.ReactNode}){return <article className="stat"><div className="stat-icon">{icon}</div><p>{label}</p><h3>{value}</h3><span>{trend}</span></article>}
export function PlaceholderPage({title,description}:{title:string;description?:string}){return <div className="placeholder"><div className="path-icon"><Sparkles/></div><h1>{title}</h1><p>{description||'This workspace is ready for your content. Connect an API when the backend is available.'}</p><Link to="/" className="btn">Back home</Link></div>}
export {ArrowRight,BookOpen,Building2,CalendarDays,Check,Code2,Mail,MessageCircle,Search,ShieldCheck,Sparkles,Star,Users,Zap};
