import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import App from './App';
import {AuthProvider} from './auth';
import {ToastProvider} from './ui-feedback';
import './styles.css';
import './styles2.css';
import './styles3.css';
import './styles4.css';
import './styles5.css';
import './styles6.css';
import './styles7.css';
import './styles8.css';
import './styles9.css';
import './styles10.css';
import './styles12.css';
import './styles13.css';
import './styles14.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><AuthProvider><ToastProvider><App/></ToastProvider></AuthProvider></BrowserRouter></React.StrictMode>);
